### PR TITLE
Fixed build types, added legend

### LINKED ISSUE #212: Build failed
```
Failed to compile./codebuild/output/src465439827/src/client/src/containers/EditRecord/Forms/CareForKidsForm.tsx
TypeScript error in /codebuild/output/src465439827/src/client/src/containers/EditRecord/Forms/CareForKidsForm.tsx(46,21):
Type '(newState: Child) => void' is not assignable to type '(_: object) => void'.
  Types of parameters 'newState' and '_' are incompatible.
    Type '{}' is missing the following properties from type 'Child': id, firstName, lastName, family  TS2322
```

### PR DESCRIPTION
**Pull request by bamader**
Closes #212 . Fixed a type casting error that was misidentifying the child object. The function should be able to run without issue now. Also added the legend for accessibility.

### CODE REVIEW

File: client/src/containers/EditRecord/Forms/CareForKidsForm.tsx [hunk 1]
```diff
@@ -49,12 +49,12 @@ export const CareForKidsForm: React.FC<CareForKidsProps> =
...
                     <FormField<Child, RadioButtonGroupProps, boolean>
                         getValue={(data) => data.at('recievesC4K')}
-                        preprocessForDisplay={(data) => data == true ? 'yes' : 'no'}
+                        preprocessForDisplay={(data) => data === true ? 'yes' : 'no'}
                         parseOnChangeEvent={(e) => {return e.target.value === 'Yes'}}
                         inputComponent={RadioButtonGroup}
                         id='c4k-radio-group'
                         name='careforkids'
-                        legend=''
+                        legend='care4kids'
```
Comment (jlhogan) [inline client/src/containers/EditRecord/Forms/CareForKidsForm.tsx:57]: if i understood melanie's explanation of legends correctly, maybe this should be `recieves care for kids` so that when it gets read with the radio options it is a meaningful chunk of information?
