### PR TITLE
959,936: fixes missing school-age funding options, fixes missing fund…

### LINKED ISSUE #936: In the Add Record process, not filling out a required field (Funding) and clicking Save does not trigger an error message
Repro steps:
1) In Roster, click Add a record
2) Fill out all information
3) Leave Funding source options unselected
4) Click Save

Result: No error message, page stays the same
Expected result: Error messaging to indicate Funding is required

image

### LINKED ISSUE #959: School age funding space options are not showing

### PR DESCRIPTION
**Pull request by jlhogan**
…ing error in create flow

closes #959 
closes #936

### CODE REVIEW

File: client/src/utils/getValidationStatus.ts [hunk 1]
```diff
@@ -42,11 +41,11 @@ export function getValidationStatusForFieldInFieldset<
 >(
   objectDriller: TObjectDriller<NonNullable<T>>,
   path: string,
-  fieldProps: any & { label: string }
+  _: any // TODO: clean this up -- no longer used now that property names come from validation error metadata
```
Comment (bamader) [inline client/src/utils/getValidationStatus.ts:44]: Maybe I'm not understanding, but what exactly needs cleaned up here?

**Review by bamader — APPROVED** [review]

File: client/src/utils/getValidationStatus.ts (hunk 1 above)
Comment (jlhogan) [reply client/src/utils/getValidationStatus.ts:44]: this unused, unnamed function argument

Comment (bamader) [reply client/src/utils/getValidationStatus.ts:44]: So it's just a note to yourself to delete it rather than a clean this up in the future?

**Review by mmazanec22 — APPROVED** [review]
