### PR TITLE
859 add funding bug

### LINKED ISSUE #859: Cannot save enrollment and funding to add child

### PR DESCRIPTION
**Pull request by mmazanec22**
Closes #859 and gets us to where we can at least add a child.  I made a few todo notes (that I will make into tickets) about some other bugs I ran into.

### CODE REVIEW

File: client/src/components/Forms/Enrollment/Fields/NewFunding.tsx [hunk 1]
```diff
@@ -61,6 +63,51 @@ export const NewFundingField = <
...
+      ),
+    };
+  });
+
+  if (isEdit) {
+    options.splice(0, 0, {
+      text: UNFUNDED,
+      id: UNFUNDED,
+      value: UNFUNDED,
+      onChange: () => {},
```
Comment (jlhogan) [inline client/src/components/Forms/Enrollment/Fields/NewFunding.tsx:107]: this doesn't appear to actually do anything, so is it worth adding?

File: client/src/components/Forms/Enrollment/Fields/Site.tsx [hunk 2]
```diff
@@ -30,6 +30,7 @@ export const SiteField = <T extends Enrollment | ChangeEnrollment>({
           e.target.value || null,
         value: `${site.id}`,
         id: `site-${site.id}`,
+        preprocessForDisplay: (data) => data === site.id,
```
Comment (jlhogan) [inline client/src/components/Forms/Enrollment/Fields/Site.tsx:33]: what does this do?

File: client/src/containers/CreateRecord/CreateRecord.tsx [hunk 3]
```diff
@@ -68,6 +68,7 @@ const CreateRecord: React.FC = () => {
             },
           ],
         });
+        return;
```
Comment (jlhogan) [inline client/src/containers/CreateRecord/CreateRecord.tsx:71]: why is this return necessary? If i'm correctly matching my parens, the only other stuff in this func is in the else

**Comment by jlhogan** [comment]
Thinking about this overnight, and my new request is instead of making the enrollment update cascade to funding, could we make the POST enrollment endpoint explicitly check for `fundings` object on the `enrollment` post body, and creating any fundings via separate db executions if they exist ?

File: client/src/components/Forms/Enrollment/Fields/NewFunding.tsx (hunk 1 above)
Comment (mmazanec22) [reply client/src/components/Forms/Enrollment/Fields/NewFunding.tsx:107]: It's a required prop.  I would argue that it should be preserved in the component lib bc this is a pretty unusual use case.

File: client/src/components/Forms/Enrollment/Fields/Site.tsx (hunk 2 above)
Comment (mmazanec22) [reply client/src/components/Forms/Enrollment/Fields/Site.tsx:33]: Radio buttons and checkboxes expect a true or false value for display-- the "checked"v alue

File: client/src/containers/CreateRecord/CreateRecord.tsx (hunk 3 above)
Comment (mmazanec22) [reply client/src/containers/CreateRecord/CreateRecord.tsx:71]: Cruft from being totally bewildered about a bug!

**Comment by mmazanec22** [comment]
What if a user tries to save without funding info, and then enters it and tries to save again?

File: client/src/components/Forms/Enrollment/Fields/NewFunding.tsx (hunk 1 above)
Comment (jlhogan) [reply client/src/components/Forms/Enrollment/Fields/NewFunding.tsx:107]: oh i mean the whole option, not specifically the onChange prop. Maybe more of a design q but if choosing unfunded doesn't delete fundings (which i dont think this does?) then we shoulldn't let people think it will. To remove a funding, they'd hae to delete the funding directly

Comment (RyanHansz) [reply client/src/components/Forms/Enrollment/Fields/NewFunding.tsx:107]: #863 removes the unfunded option

Comment (RyanHansz) [reply client/src/components/Forms/Enrollment/Fields/NewFunding.tsx:107]: #863 removes the unfunded option

File: client/src/components/Forms/Enrollment/Fields/EnrollmentStartDate.tsx [hunk 4]
```diff
@@ -21,14 +21,21 @@ export const EnrollmentStartDateField = <
...
   enrollmentAccessor = (data) => data as TObjectDriller<Enrollment>,
 }: EnrollmentStartDateProps<T>) => {
+  // TODO: why does this not show up after save during create child?
+  // To reproduce: add child, save without completely filling out enrollment form (but include entry)
   return (
     <FormField<T, DateInputProps, Moment | null>
-      getValue={(data) => enrollmentAccessor(data).at('entry')}
-      parseOnChangeEvent={(e: any) => e}
+      getValue={(data) => {
+        console.log(data);
```
Comment (jlhogan) [inline client/src/components/Forms/Enrollment/Fields/EnrollmentStartDate.tsx:29]: nit: console.logs

File: client/src/components/Forms/Enrollment/Fields/EnrollmentStartDate.tsx [hunk 5]
```diff
@@ -21,14 +21,21 @@ export const EnrollmentStartDateField = <
...
+        return enrollmentAccessor(data).at('entry');
+      }}
+      parseOnChangeEvent={(e) => {
+        console.log(e);
```
Comment (jlhogan) [inline client/src/components/Forms/Enrollment/Fields/EnrollmentStartDate.tsx:33]: and here

File: client/src/components/Forms/FamilyIncome/Form.tsx [hunk 6]
```diff
@@ -108,6 +108,8 @@ export const FamilyIncomeForm: React.FC<FamilyIncomeFormProps> = ({
     child?.family?.incomeDeterminations?.find(
       (d) => d.id === incomeDeterminationId
     ) || ({} as IncomeDetermination);
+  // TODO: if we're in the create record flow, just find the income det that exists
```
Comment (jlhogan) [inline client/src/components/Forms/FamilyIncome/Form.tsx:111]: this existed at some point, and brandon merged a change to get rid of it b/c it was causing smething weird (presumably in the edit flow) so i think we'll need to distinguish between edit/create in this form

**Review by jlhogan — APPROVED** [review]

File: client/src/components/Forms/FamilyIncome/Form.tsx (hunk 6 above)
Comment (bamader) [reply client/src/components/Forms/FamilyIncome/Form.tsx:111]: Yeah Ryan wanted creating new dets to not prefill with the information from the existing det

**Review by bamader — APPROVED** [review]

File: client/src/components/Forms/FamilyIncome/Form.tsx (hunk 6 above)
Comment (jlhogan) [reply client/src/components/Forms/FamilyIncome/Form.tsx:111]: mhm mhm, so here if we're in create flow then look for existing det, otherwise empty det

Comment (bamader) [reply client/src/components/Forms/FamilyIncome/Form.tsx:111]: Other way around, right? Create uses a blank and edit searches for existing?
