### PR TITLE
Birth cert bugs

### LINKED ISSUE #869: US Birth Certificate fields should be shown by default on a child record when there is information entered
Right now it only shows the radio button for US Birth Certificate selected

(radio button expansion is not expanded even tho correct radio option is selected)

### LINKED ISSUE #887: Add child: Issues with identifiers section
In staging and Production for at least TVCCA:
When adding a new child record from the roster:
## [See video of bugs here](https://drive.google.com/file/d/13h5phq5MUR4i7B6xIqP4v0rzPEKyC7ml/view?usp=sharing)

- US birth certificate radio button is unchecking when I enter town or state info (related to #869 ?)
- On save, all required fields are flagged as missing, despite having information entered. 
  - Users can only resolve this by cutting and pasting the values into the field and hitting save again

- Unique identifiers and SASID #s are being reformatted:
Screen Shot 2020-12-08 at 11 23 50 AM

- Refreshing the page shows this error:
Screen Shot 2020-12-08 at 11 18 24 AM

### PR DESCRIPTION
**Pull request by mmazanec22**
Closes #869 and closes #887

### CODE REVIEW

**Review by jlhogan — APPROVED** [review]

File: client/src/components/Forms/ChildIdentifiers/Fields/BirthState.tsx [hunk 1]
```diff
@@ -7,62 +9,40 @@ import {
...
  * Component for entering the birth state of a child in an enrollment.
  */
-export const BirthStateField: React.FC<StateFieldProps> = ({ child }) => {
+export const BirthStateField: React.FC = () => {
   // Use state to control clearing input when one component or the other is manipulated
-  const [state, setState] = useState<string | null>(null);
-  const { dataDriller, updateData } = useGenericContext<Child>(FormContext);
-
-  // Can't parse undefined visually, so need conversion from null
-  useEffect(() => {
```
Comment (JordanGuinn) [inline client/src/components/Forms/ChildIdentifiers/Fields/BirthState.tsx:25]: +10000000 for getting rid of this nested ternary 🎉

**Review by JordanGuinn — APPROVED** [review]
