### PR TITLE
762-714-child-get-fixes

### LINKED ISSUE #714: When batch uploading records with changes in age group, the record is displayed in the wrong age group section.
## Add array entity sort on multi-child GET request
Screen Shot 2020-11-10 at 2 12 27 PM
Screen Shot 2020-11-10 at 2 09 52 PM

### LINKED ISSUE #762: When batch uploading a record with multiple enrollments, two separate child records are being created.
@jlhogan feel free to add more to this one

### PR DESCRIPTION
**Pull request by jlhogan**
closes #714 
closes #762

### CODE REVIEW

File: src/controllers/children/get.ts [hunk 1]
```diff
@@ -162,3 +162,50 @@ const getFindOpts = async (
...
+ * 	- remove deleted entities
+ * 	- sort entities by date
+ * 	- validate full object tree
+ * @param child
+ */
+const postProcessChild = async (child: Child) => {
+  removeDeletedEntitiesFromChild(child);
+  sortEntities(child);
+  return validateObject(child);
+};
```
Comment (bamader) [inline src/controllers/children/get.ts:177]: Was _def_ time we just gave  ourselves a post-processing func. We certainly do enough to  need one.

**Review by bamader — APPROVED** [review]
Looks good. Glad all these bugs are just getting annihilated (although do we need to be worried that neither of us could repro some of those batch upload bugs?). I have no idea what went wrong with the find `opts` in `getById` but maybe it was the parentheses around the SQL? Before I  threw out the query builder stuff for being overly complicated I thought it was pretty finnicky.

**Comment by jlhogan** [comment]
>I have no idea what went wrong with the find opts in getById but maybe it was the parentheses around the SQL

same analysis, altho what was happening as a result of that is a mystery i don't care to solve
