### PR TITLE
469 error boundary

### LINKED ISSUE #469: Error boundary: Something went wrong with mail:to help link
Throw an exception instead of showing a blank page. 

– Wrap the (main?) component tree in error boundary from the component library.

Sprinkle throughout!

### PR DESCRIPTION
**Pull request by mmazanec22**
Closes #469 

This standardizes how we handle errors across the app and adds lots of error boundaries at varying levels to to try to make sure the user is bothered as little as possible by errors when they do occur.

### CODE REVIEW

File: client/src/containers/BatchEdit/BatchEdit.tsx [hunk 1]
```diff
@@ -93,10 +96,8 @@ const BatchEdit: React.FC = () => {
       <h1 ref={h1Ref} className="margin-bottom-1">
         Add needed information
       </h1>
-      {isValidating ? (
-        <>Loading</>
-      ) : (
-        <>
+      <LoadingWrapper loading={isValidating}>
```
Comment (jlhogan) [inline client/src/containers/BatchEdit/BatchEdit.tsx:99]: this was just already wrong but while you're touching it maybe better to update this to use `!children` instead of `isValidating`

File: client/src/containers/App/App.tsx [hunk 2]
```diff
@@ -1,73 +1,79 @@
...
-      />
-      <main id="main-content">
-        <Switch>
-          {routes.map((route, index) => (
-            <MakeRouteWithSubRoutes key={index} {...route} />
-          ))}
-        </Switch>
-      </main>
+      {/* In case it really hits the fan and not even the header works */}
+      <ErrorBoundary alertProps={{ ...defaultErrorBoundaryProps }}>
```
Comment (jlhogan) [inline client/src/containers/App/App.tsx:17]: why is the spread necessary ?

File: client/src/containers/CreateRecord/CreateRecord.tsx [hunk 3]
```diff
@@ -122,7 +119,13 @@ const CreateRecord: React.FC = () => {
       <p className="usa-hint">
         Information is required unless otherwise specified.
       </p>
-      <StepList steps={steps} props={commonFormProps} activeStep={activeStep} />
+      <ErrorBoundary alertProps={{ ...defaultErrorBoundaryProps }}>
```
Comment (jlhogan) [inline client/src/containers/CreateRecord/CreateRecord.tsx:122]: should this also get a loading wrapper?

File: client/src/containers/EditRecord/EditRecord.tsx [hunk 4]
```diff
@@ -45,37 +51,41 @@ const EditRecord: React.FC = () => {
...
+      .catch((err) => {
+        throw new Error(err);
+      });
   }, [accessToken, childId, triggerRefetchCounter]);
 
   useFocusFirstError([child]);
 
   if (!child) {
-    return <></>;
+    return <LoadingWrapper loading={true} />;
```
Comment (jlhogan) [inline client/src/containers/EditRecord/EditRecord.tsx:88]: should this indeed wrap the form content?

File: client/src/containers/EditRecord/EnrollmentFunding/ChangeEnrollment/Card.tsx [hunk 5]
```diff
@@ -4,15 +4,16 @@ import {
...
 } from '@ctoec/component-library';
 import { Enrollment, Child } from '../../../../shared/models';
 import { ChangeEnrollmentForm } from './Form';
+import { RecordFormProps } from '../../../../components/Forms';
 
 type ChangeEnrollmentCardProps = {
   child: Child;
   currentEnrollment?: Enrollment;
   afterSaveSuccess: () => void;
+  setAlerts: RecordFormProps['setAlerts'];
```
Comment (jlhogan) [inline client/src/containers/EditRecord/EnrollmentFunding/ChangeEnrollment/Card.tsx:16]: should maybe be able to make this
```
type ChangeEnrollmentCardProps = RecordFormProps &  { currentEnrollment?: Enrollment
```

File: client/src/containers/EditRecord/EnrollmentFunding/ChangeFunding/Card.tsx [hunk 6]
```diff
@@ -2,11 +2,13 @@ import React, { useState } from 'react';
 import { Card, Button, Alert } from '@ctoec/component-library';
 import { Enrollment } from '../../../../shared/models';
 import { ChangeFundingForm } from './Form';
+import { RecordFormProps } from '../../../../components/Forms';
 
 type ChangeFundingCardProps = {
```
Comment (jlhogan) [inline client/src/containers/EditRecord/EnrollmentFunding/ChangeFunding/Card.tsx:7]: same here re RecordFormProps

File: client/src/containers/EditRecord/EnrollmentFunding/EditEnrollmentCard.tsx [hunk 7]
```diff
@@ -7,19 +7,20 @@ import {
...
 import { EnrollmentForm } from '../../../components/Forms/Enrollment/Form';
+import { RecordFormProps } from '../../../components/Forms';
 
 type EditEnrollmentCardProps = {
   child: Child;
   enrollmentId: number;
-  isCurrent?: boolean;
   afterSaveSuccess: () => void;
+  isCurrent?: boolean;
+  setAlerts: RecordFormProps['setAlerts'];
```
Comment (jlhogan) [inline client/src/containers/EditRecord/EnrollmentFunding/EditEnrollmentCard.tsx:23]: and here

File: client/src/containers/EditRecord/EnrollmentFunding/EditFundingCard.tsx [hunk 8]
```diff
@@ -10,18 +10,19 @@ import {
...
 import { FundingForm } from '../../../components/Forms/Enrollment/Funding/Form';
+import { RecordFormProps } from '../../../components/Forms';
 
 type EditFundingCardProps = {
   child: Child;
   fundingId: number;
   enrollmentId: number;
   isCurrent?: boolean;
   afterSaveSuccess: () => void;
+  setAlerts: RecordFormProps['setAlerts'];
```
Comment (jlhogan) [inline client/src/containers/EditRecord/EnrollmentFunding/EditFundingCard.tsx:25]: and here :)

**Review by jlhogan — APPROVED** [review]

**Review by bamader — APPROVED** [review]

File: client/src/containers/App/App.tsx (hunk 2 above)
Comment (mmazanec22) [reply client/src/containers/App/App.tsx:17]: Whoops, totally isn't

File: client/src/containers/CreateRecord/CreateRecord.tsx (hunk 3 above)
Comment (mmazanec22) [reply client/src/containers/CreateRecord/CreateRecord.tsx:122]: I think it would make sense to put this around the individual forms, since that would make the whole steplist flash to a loading icon between steps, which seems kind of jarring

File: client/src/containers/EditRecord/EnrollmentFunding/ChangeEnrollment/Card.tsx (hunk 5 above)
Comment (mmazanec22) [reply client/src/containers/EditRecord/EnrollmentFunding/ChangeEnrollment/Card.tsx:16]: That would require us to pass all of the props through though so we could have access to all of the required values.  I only really want this one property to be required on these nested forms.
