### PR TITLE
812 multi site tabnav fixes

### LINKED ISSUE #812: Multi-site tab-nav fixes
- some sites are not visible (appear hidden behind the empty roster alert), 

- the site dropdown isn't styled, 

- and a site selected from drop-down isn't being brought to the front of the site tabs

- Truncated (...) site names need to show in full in a tooltip when the user hovers on that tab

image

image

### PR DESCRIPTION
**Pull request by mmazanec22**
Closes #812 

Depends on https://github.com/ctoec/component-library/pull/98

### CODE REVIEW

File: client/src/containers/Roster/Roster.tsx [hunk 1]
```diff
@@ -97,14 +96,11 @@ const Roster: React.FC = () => {
...
     superHeaderText,
-  } = useOrgSiteProps(
-    !children || !query.organization,
-    (children || []).length,
-    (siteFilteredChildren || []).length
-  );
+  } = useOrgSiteProps(loading, (children || []).length);
 
+  const siteChildCount = (siteFilteredChildren || []).length;
+  const rosterH2 = getRosterH2(siteChildCount, user?.sites, query);
```
Comment (mmazanec22) [inline client/src/containers/Roster/Roster.tsx:103]: We needed to move this here so that our memoized tabnav values didn't need to re-calculate when the site stuff changed

File: client/src/containers/Roster/hooks/useOrgSiteProps.tsx [hunk 2]
```diff
@@ -11,112 +11,102 @@ import pluralize from 'pluralize';
...
-) => {
+export const useOrgSiteProps = (isLoading: boolean, orgChildCount: number) => {
+  const history = useHistory();
   const { user } = useContext(UserContext);
-  const organizations = user?.organizations || [];
-  const sites = user?.sites || [];
 
-  const history = useHistory();
-  const query = parse(history.location.search) as RosterQueryParams;
+  return useMemo(() => {
```
Comment (mmazanec22) [inline client/src/containers/Roster/hooks/useOrgSiteProps.tsx:18]: Memoizing these values prevents the tab nav props from being a different object on every change (which was triggering the tab nav to recompute its secondary tabs items)

**Review by jlhogan — APPROVED** [review]

**Review by bamader — APPROVED** [review]
