### PR TITLE
Fix ie thing, maybe

### LINKED ISSUE #551: App doesn't work in IE
See browserstack

### PR DESCRIPTION
**Pull request by mmazanec22**
Closes #551 

~Not ready for review just yet, gotta make a PR so I can use QA env in BrowserStack~

Edit: this appears to have fixed it, yay!

### CODE REVIEW

**Review by jlhogan — APPROVED** [review]
HUZZAH!!!!! what a nice lil fix

File: client/src/index.tsx [hunk 1]
```diff
@@ -1,3 +1,6 @@
+// https://stackoverflow.com/questions/56421417/react-app-not-working-in-internet-explorer-11
+import 'react-app-polyfill/ie11';
+import 'react-app-polyfill/stable';
```
Comment (kmagida110) [inline client/src/index.tsx:3]: Very strange that importing this package does all that it needs to do but hey, it works!

**Review by kmagida110 — APPROVED** [review]
